### ISSUE TITLE
Error al instalar en Centos 7

### ISSUE THREAD

**Issue by ricbarm** [SowerPHP/sowerpkg#1]
Estimado, al intentar instalar el framework SowerPHP con SowerPKG, me aparece el siguiente error:

> Creando projecto web... sed: -e expression #1, char 52: unknown option to `s'

Por lo que pude ver el error informado es el de la linea 172

La instalación es la de por defecto

`> $ ./sowerpkg.sh install`

Tengo instalado todos los requerimientos:
Apache, PHP 5.5, MariaDB, Git, Mercurial y Composer
También lo intente cambiando el directorio con `-w`, sin embargo el error persiste.

Saludos

**Comment by estebandelaf** [comment]
Hola,

Gracias por el reporte, había un problema con el comando sed que se usa para ajustar el directorio del framework en caso que se instale como compartido, fue corregido[1]

Saludos!

[1] https://github.com/SowerPHP/sowerpkg/commit/43fd9bedc7ce4b88e6b0df205fd5535a8e594d06
